version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"

  jobs:
    post_install:
      - pip install pdoc3
      - pdoc --html --output-dir $READTHEDOCS_OUTPUT/html skytools

conda:
  environment: environment.yml