version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

  commands:
    - pip3 install numpy
    - pip3 install astropy
    - pip3 install healpy
    - pip3 install scipy 
    - pip3 install joblib
    - pip3 install pdoc3
    - pdoc --html --output-dir $READTHEDOCS_OUTPUT/html

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: ./requirements.txt
    - method: pip
      path: .