version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

  commands:
    - pip install numpy, astropy, healpy, scipy, joblib, pkg-config, meson, pdoc3
    - pdoc --html --output-dir $READTHEDOCS_OUTPUT/html skytools
