version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "miniconda-latest"
  conda:
    environment: uEnv.yml
  commands:
    - pip install pdoc3
    - pdoc --html --output-dir $READTHEDOCS_OUTPUT/html skytools