version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

  commands:
    - pip install pdoc3
    - pdoc --html --output-dir $READTHEDOCS_OUTPUT/html skytools

# Explicitly set the version of Python and its requirements
python:
  - install:
    - requirements: ./requirements.txt
    - method: pip