{% set name = "skytools" %}
{% set version = "0.0.1b5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/1cosmologist/skytools/archive/v{{ version }}.tar.gz
  sha256: 5aa3e4d8854885723d2ae43044da1dada8023de807e0accd3dfc8e8693aefb1f

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true    # [win or py<39]
  number: 0



requirements:
  host:
    - python
    - meson-python
    - pkg-config
    - pip
  run:
    - python
    - astropy
    - healpy >=1.16.0
    - numpy
    - scipy
    - joblib
    

test:
  imports:
    - skytools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/1cosmologist/skytools
  summary: A library of useful tools for CMB data analysis.
  license: GPL-3.0-only
  license_file: LICENSE.txt
  doc_url: https://skytools.readthedocs.io/latest/

extra:
  recipe-maintainers:
    - 1cosmologist
